export enum AggregationRule {
  ALL_MANDATORY = 'ALL_MANDATORY',
  ALL_MANDATORY_AND_THRESHOLD = 'ALL_MANDATORY_AND_THRESHOLD',
  ALL_MANDATORY_AND_WEIGHTED_CONFIDENCE = 'ALL_MANDATORY_AND_WEIGHTED_CONFIDENCE',
}
